"""new

Revision ID: 04cc5cab8351
Revises: 16f93777280d
Create Date: 2024-04-11 23:05:41.148011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cc5cab8351'
down_revision = '16f93777280d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_nik_key', type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('nik')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('users_nik_key', ['nik'])

    # ### end Alembic commands ###
