"""user passord

Revision ID: 071248b2c68d
Revises: 04cc5cab8351
Create Date: 2024-04-12 12:16:01.773809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071248b2c68d'
down_revision = '04cc5cab8351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['nik'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('nik')

    # ### end Alembic commands ###
