"""confirmed

Revision ID: 16356d78f9a5
Revises: 7d90c442e96a
Create Date: 2024-04-19 23:45:27.227948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16356d78f9a5'
down_revision = '7d90c442e96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
