"""nik

Revision ID: 7d90c442e96a
Revises: 76470015a839
Create Date: 2024-04-12 13:48:16.065575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d90c442e96a'
down_revision = '76470015a839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint('answers_nick_key', type_='unique')
        batch_op.drop_index('ix_answers_username')
        batch_op.create_index(batch_op.f('ix_answers_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_username'))
        batch_op.create_index('ix_answers_username', ['username'], unique=True)
        batch_op.create_unique_constraint('answers_nick_key', ['nick'])

    # ### end Alembic commands ###
