"""empty message

Revision ID: 8ffad8353266
Revises: a6915187fea2
Create Date: 2024-05-16 10:07:09.708914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffad8353266'
down_revision = 'a6915187fea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('since', sa.String(length=200), nullable=False),
    sa.Column('forend', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserve_id'), ['id'], unique=False)

    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartment', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('reserve', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserve_id'))

    op.drop_table('reserve')
    # ### end Alembic commands ###
